# Libreria Pandas

In [1]:
import pandas as pd

In [12]:
#las series tienen un índice asociado a cada elemento, que por defecto es un número entero que comienza en 0
serie=pd.Series([100, 200, 300, 400, 500])
print(serie)
print(serie[0])
#serie indezada a partir de uma lista de índices
serie2=pd.Series([100, 200, 300, 400, 500], index=['a', 'b', 'c', 'd', 'e'])
print(serie2)
print(serie2['b'])
print(serie2.iloc[3]) #acceso por posición posicion 0,1,2,3,4
print(serie2.loc["a"]) #acceso por etiqueta o index

0    100
1    200
2    300
3    400
4    500
dtype: int64
100
a    100
b    200
c    300
d    400
e    500
dtype: int64
200
400
100

In [26]:
# DataFrame es una estructura de datos tabular, con filas y columnas, similar a una hoja de cálculo o una tabla SQL. Cada columna puede tener un tipo de dato diferente (números, texto, fechas, etc.) y cada fila representa un registro o una observación. Los DataFrames son ampliamente utilizados en análisis de datos y manipulación de datos debido a su flexibilidad y facilidad de uso.
#axis=1 se refiere a las columnas, mientras que axis=0 se refiere a las filas.Por ejemplo:
#si quieres eliminar una columna específica de un DataFrame, usarías axis=1, mientras que si quieres eliminar una fila específica, usarías axis=0.
#creamos un DataFrame a partir de un diccionario de listas
data={'Nombre': ['Juan', 'Ana', 'Pedro', 'María', 'Luis'],
      'Edad': [25, 30, 35, 40, 45],
      'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao']}
df3=pd.DataFrame(data)
print(df3)

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    30  Barcelona
2  Pedro    35   Valencia
3  María    40    Sevilla
4   Luis    45     Bilbao

In [ ]:
pd.read_csv("C:/Users/TuUsuario/Desktop/datos.csv")
pd.read_excel("archivo.xlsx")
pd.read_json("archivo.json")
df.to_csv("archivo.csv", index=False)
df.to_excel("archivo.xlsx", index=False)
df.to_json("archivo.json", orient="records", lines=True)

In [17]:
#mostrar sin print y archivo en otra carpeta distinta.
df=pd.read_csv("C:\Curso Ciencia de Datos Talento Digital\Data ejemplos\winequality.csv")
df.head()

,Unnamed: 0,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,2,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
#Mostrar con print y buscar el archivo en la carpeta de trabajo actual.
df1=pd.read_csv("winequality1.csv")
print(df1)

      Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.4              0.70         0.00
1              2            7.8              0.88         0.00
2              3            7.8              0.76         0.04
3              4           11.2              0.28         0.56
4              5            7.4              0.70         0.00
...          ...            ...               ...          ...
6492        6493            6.2              0.21         0.29
6493        6494            6.6              0.32         0.36
6494        6495            6.5              0.24         0.19
6495        6496            5.5              0.29         0.30
6496        6497            6.0              0.21         0.38

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0                1.9      0.076                 11.0                  34.0
1                2.6      0.098                 25.0                  67.0
2                2.3      0.092                 15.0                  54.0
3                1.9      0.075                 17.0                  60.0
4                1.9      0.076                 11.0                  34.0
...              ...        ...                  ...                   ...
6492             1.6      0.039                 24.0                  92.0
6493             8.0      0.047                 57.0                 168.0
6494             1.2      0.041                 30.0                 111.0
6495             1.1      0.022                 20.0                 110.0
6496             0.8      0.020                 22.0                  98.0

      density    pH  sulphates  alcohol  quality
0     0.99780  3.51       0.56      9.4        5
1     0.99680  3.20       0.68      9.8        5
2     0.99700  3.26       0.65      9.8        5
3     0.99800  3.16       0.58      9.8        6
4     0.99780  3.51       0.56      9.4        5
...       ...   ...        ...      ...      ...
6492  0.99114  3.27       0.50     11.2        6
6493  0.99490  3.15       0.46      9.6        5
6494  0.99254  2.99       0.46      9.4        6
6495  0.98869  3.34       0.38     12.8        7
6496  0.98941  3.26       0.32     11.8        6

[6497 rows x 13 columns]

In [ ]:
print(df.loc[:,"density"].head()) # : indica todas las filas y "density" la columna     
print("-----------------------------")
print(df.loc[:,["density"]].head()) #loc para la etiqueta de columna "density"
print("-----------------------------")
print(df.iloc[:,[1]].head()) #iloc para la posicion de columna 1

0    0.9978
1    0.9968
2    0.9970
3    0.9980
4    0.9978
Name: density, dtype: float64
-----------------------------
   density
0   0.9978
1   0.9968
2   0.9970
3   0.9980
4   0.9978
-----------------------------
   fixed.acidity
0            7.4
1            7.8
2            7.8
3           11.2
4            7.4

In [24]:
df

,Unnamed: 0,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,2,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6493,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6493,6494,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
6494,6495,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
6495,6496,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
6496,6497,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [ ]:
df3[df3["Edad"]>33] #filtrar acceso a la columna "Edad"

  Nombre  Edad    Ciudad
2  Pedro    35  Valencia
3  María    40   Sevilla
4   Luis    45    Bilbao

In [32]:
print(df.head(2)) #2 primeras filas
print("---------------")
print(df.tail(2)) #2 últimas filas
print("---------------")
print(df.info())
print("---------------")
print(df.describe())

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    30  Barcelona
---------------
  Nombre  Edad   Ciudad
3  María    40  Sevilla
4   Luis    45   Bilbao
---------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      object
 1   Edad    5 non-null      int64
 2   Ciudad  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes
None
---------------
            Edad
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000

In [39]:
print(df3["Edad"].min()) #minimo de la columna "Edad"
print(df3["Edad"].max()) #maximo de la columna "Edad"
print(df3["Edad"].mean()) #media de la columna "Edad"
print(df3["Edad"].median()) #mediana de la columna "Edad"
print(df3["Edad"].std()) #desviación estándar de la columna "Edad"
print(df3["Edad"].count()) #número de valores de la columna "Edad"
print(df3["Edad"].sum()) #suma de los valores de la columna "Edad"
print("---------------")

valoresUnicos=df3["Ciudad"].value_counts() #conteo de valores únicos en la columna "Ciudad"
print(valoresUnicos)
print("---------------")
print("frecuencia relativa (%):",df3["Ciudad"].value_counts(normalize=True) * 100) #frecuencia relativa de valores únicos en la columna "Ciudad"
print("---------------")
print("valores únicos:",df3["Ciudad"].unique()) #valores únicos en la columna "Ciudad"
print("---------------")
print("numero de valores únicos:",df3["Ciudad"].nunique()) #número de valores únicos en la columna "Ciudad"

25
45
35.0
35.0
7.905694150420948
5
175
---------------
Ciudad
Madrid       1
Barcelona    1
Valencia     1
Sevilla      1
Bilbao       1
Name: count, dtype: int64
---------------
frecuencia relativa (%): Ciudad
Madrid       20.0
Barcelona    20.0
Valencia     20.0
Sevilla      20.0
Bilbao       20.0
Name: proportion, dtype: float64
---------------
valores únicos: ['Madrid' 'Barcelona' 'Valencia' 'Sevilla' 'Bilbao']
---------------
numero de valores únicos: 5

In [40]:
df3.columns #nombres de las columnas del DataFrame df3

Index(['Nombre', 'Edad', 'Ciudad'], dtype='object')

In [41]:
df3.shape

(5, 3)

In [42]:
#PENDIENTE METODOS DE AGRUPACION Y AGRUPACION POR VALORES UNICOS EN UNA COLUMNA
agrupacion=df3.groupby("Ciudad") #agrupación por la columna "Ciudad"
print(agrupacion["Edad"].mean()) #media de la columna "Edad" para cada grupo de la columna "Ciudad"

Ciudad
Barcelona    30.0
Bilbao       45.0
Madrid       25.0
Sevilla      40.0
Valencia     35.0
Name: Edad, dtype: float64

In [43]:
#guardar el DataFrame df3 en un archivo CSV
df3.to_csv("ejemplo_guardar_df3.csv", index=False)